-- Schema Version: 20251223
-- Base Schema: memogarden-core-v1
-- Description: Initial schema with entity registry and transactions
--
-- Schema Philosophy:
-- - Global entity registry stores common metadata for all entity types
-- - Type-specific tables store only domain attributes
-- - Accounts and categories are labels (simple TEXT), not relational entities
-- - Schema version tracked in _schema_metadata for migration tracking
-- - Fresh databases apply current schema; existing databases migrate forward-only
-- - After successful migration, schema snapshots archived to Soil for agent reference

-- Schema metadata table (for version tracking and migration management)
CREATE TABLE IF NOT EXISTS _schema_metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

INSERT INTO _schema_metadata VALUES
    ('version', '20251223', datetime('now')),
    ('base_schema', 'memogarden-core-v1', datetime('now')),
    ('description', 'Initial schema with entity registry and transactions', datetime('now'));

-- Global entity registry (common metadata for ALL entity types)
CREATE TABLE IF NOT EXISTS entity (
    id TEXT PRIMARY KEY,              -- Plain UUID (generated by Python)
    type TEXT NOT NULL,               -- Entity table name: 'transactions', 'recurrences', etc.
    group_id TEXT,                    -- Optional grouping/clustering of related entities
    superseded_by TEXT,               -- Reclassification: points to superseding entity
    superseded_at TEXT,               -- ISO 8601 timestamp of supersession
    derived_from TEXT,                -- Provenance: points to source entity
    created_at TEXT NOT NULL,         -- ISO 8601 timestamp
    updated_at TEXT NOT NULL,         -- ISO 8601 timestamp

    FOREIGN KEY (group_id) REFERENCES entity(id),
    FOREIGN KEY (superseded_by) REFERENCES entity(id),
    FOREIGN KEY (derived_from) REFERENCES entity(id)
);

CREATE INDEX IF NOT EXISTS idx_entity_type ON entity(type);
CREATE INDEX IF NOT EXISTS idx_entity_created ON entity(created_at);
CREATE INDEX IF NOT EXISTS idx_entity_superseded ON entity(superseded_by);
CREATE INDEX IF NOT EXISTS idx_entity_group ON entity(group_id);

-- Transactions table (domain-specific attributes only)
CREATE TABLE IF NOT EXISTS transactions (
    id TEXT PRIMARY KEY,
    amount REAL NOT NULL,
    currency TEXT NOT NULL DEFAULT 'SGD',
    transaction_date TEXT NOT NULL,  -- ISO 8601 date (YYYY-MM-DD)
    description TEXT NOT NULL DEFAULT '',  -- Short title (e.g., "Coffee at Starbucks")
    account TEXT NOT NULL,            -- Label: e.g., "Household", "Personal"
    category TEXT,                    -- Label: e.g., "Food", "Transport"
    author TEXT NOT NULL DEFAULT 'system',
    recurrence_id TEXT,               -- FK to entity (type='recurrences')
    notes TEXT,                       -- Optional longer details

    FOREIGN KEY (id) REFERENCES entity(id) ON DELETE CASCADE,
    FOREIGN KEY (recurrence_id) REFERENCES entity(id)
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(transaction_date);
CREATE INDEX IF NOT EXISTS idx_transactions_account ON transactions(account);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category);

-- Convenient view for querying transactions with metadata
CREATE VIEW IF NOT EXISTS transactions_view AS
SELECT
    t.*,
    e.created_at,
    e.updated_at,
    e.superseded_by,
    e.superseded_at,
    e.group_id,
    e.derived_from
FROM transactions t
JOIN entity e ON t.id = e.id;
